# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "money-mongoid"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-09-24"
  s.description = "Makes it easy to use money with mongoid"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/money-mongoid.rb",
    "lib/money/mongoid.rb",
    "lib/money/mongoid/2x/money.rb",
    "lib/money/mongoid/3x/money.rb",
    "lib/money/mongoid/3x/origin/selectable.rb",
    "lib/money/mongoid/core_ext.rb",
    "lib/money/mongoid/core_ext/array.rb",
    "lib/money/mongoid/core_ext/range.rb",
    "lib/money/mongoid/core_ext/string.rb",
    "lib/money/mongoid/macros.rb",
    "lib/money/mongoid/monetizable.rb",
    "lib/money/mongoid/monetize.rb",
    "lib/money/orm/generic.rb",
    "money-mongoid.gemspec",
    "spec/money/mongoid/2x/money_spec.rb",
    "spec/money/mongoid/2x/product.rb",
    "spec/money/mongoid/3x/money_spec.rb",
    "spec/money/mongoid/3x/product.rb",
    "spec/money/mongoid/models.rb",
    "spec/money/mongoid/models/account.rb",
    "spec/money/mongoid/models/price.rb",
    "spec/money/mongoid/monetize_spec.rb",
    "spec/money/mongoid/shared_ex.rb",
    "spec/money/mongoid/spec_helper.rb",
    "spec/money/mongoid/support/mongoid.yml",
    "spec/money/mongoid/version_setup.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/money-mongoid"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Mongoid support and integration for the money gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<money>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid>, ["~> 3"])
      s.add_runtime_dependency(%q<origin>, [">= 0"])
      s.add_runtime_dependency(%q<moped>, [">= 0"])
      s.add_runtime_dependency(%q<origin-selectable_ext>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.10"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<money>, [">= 0"])
      s.add_dependency(%q<mongoid>, ["~> 3"])
      s.add_dependency(%q<origin>, [">= 0"])
      s.add_dependency(%q<moped>, [">= 0"])
      s.add_dependency(%q<origin-selectable_ext>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.10"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<money>, [">= 0"])
    s.add_dependency(%q<mongoid>, ["~> 3"])
    s.add_dependency(%q<origin>, [">= 0"])
    s.add_dependency(%q<moped>, [">= 0"])
    s.add_dependency(%q<origin-selectable_ext>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.10"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.1.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

